export const projects = [
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho1", description: "Projeto laguinho", org: "OpendevUFCG" },
];