export const projects = [
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
  { name: "Laguinho", description: "Projeto laguinho", org: "OpendevUFCG" },
];
