import type { QueryOptions } from '@prismicio/client/types/ResolvedApi'
import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import SliceZone from '../components/home/SliceZone'
import ScheduleCard from '../components/home/ScheduleCard'

import { Client } from '../lib/prismic'
import { Stack } from '@chakra-ui/layout'

export const getStaticProps: GetStaticProps = async ({ previewData = {} }) => {
  const { ref } = previewData as QueryOptions
  const client = Client()

  const doc = (await client.getSingle('homepage', ref ? { ref } : {})) || {}

  return {
    props: {
      doc,
    },
  }
}

const Home: NextPage = ({
  doc,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const startDate = new Date(2018, 9, 8, 19, 30)
  const endDate = new Date(2018, 9, 8, 20, 30)

  return (
    <>
      <Head>
        <title>Home - Andromedev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {doc.data.body.map((slice: unknown, idx: number) => (
        <SliceZone key={idx} slice={slice} />
      ))}

      <Stack
        direction="row"
        padding="6"
        backgroundColor="#50339A"
        spacing="24px"
      >
        <ScheduleCard
          title="Abertura de inscrição de organizações"
          startTime={startDate}
          endTime={endDate}
          place="Discord"
          placeLink="discord.gg"
        />
        <ScheduleCard
          title="Abertura de inscrição de organizações"
          startTime={startDate}
          endTime={endDate}
          place="Discord"
          placeLink="discord.gg"
        />
      </Stack>
    </>
  )
}

export default Home
