import type { NextPage } from "next";
import Head from "next/head";

const Titulo = ({ titulo }: { titulo: string }) => <h1>{titulo}</h1>;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home - Andromedev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Titulo titulo="Aqui haverá a home do site do Andromedev" />
    </div>
  );
};

export default Home;
